name: page publish #发布名称

on:  
  push: #触发方式
    branches: 
      - master #触发分支

jobs: #脚本内容
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: snap install hugo --channel=extended
    - run: hugo -D
    - run: cp CNAME public/ #指定gitpage的自定义域名

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        PUBLISH_BRANCH: gh-pages #发布到的分支
        PUBLISH_DIR: public #需要发布的内容
