name: page publish #发布名称

on:  
  push: #触发方式
    branches: 
      - master #触发分支

jobs: #脚本内容
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: sudo snap install hugo --channel=extended
    - run: hugo -D
    - run: sudo mkdir docs
    - run: sudo mv public/* docs/ 
    - run: sudo mv docs public/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        PUBLISH_BRANCH: pages #发布到的分支
        PUBLISH_DIR: public #需要发布的内容
